version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myb-coinbase-pro-trade"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wey34ou6ahuw"
s3_prefix = "myb-coinbase-pro-trade"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
