AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  myb-coinbase-pro-trade

  Serverless capabilities for managing aspects of a mining business

Resources:
  # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  CoinbaseProTradeBtcFn:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: coinbase_pro_trade_btc_function
      Handler: coinbase_pro_trade_btc.app.lambda_handler
      Runtime: python3.8
      Timeout: 3
      Environment:
        Variables:
          # If RUN_MODE is 'test', runs in test mode
          RUN_MODE: "test"
          TRADES_CURRENCY: BTC
          TRADES_PRODUCT_ID: BTC-USD
          # The maximum number of data points for a single request is 300 candles,
          # so at 1-day granularity you can't have more than 300 days
          TRADES_DAY_RANGE_EVAL: 250
          TRADES_FUNCTION: max
          TRADES_TYPE: limit
          # the minimum amount required to trade the specified currency
          TRADES_MIN_AMOUNT: 10.00
          # Options are min, hour, day
          TRADES_CANCEL_AFTER: day
          # Details about Coinbase Pro API keys: https://docs.pro.coinbase.com/
          CBP_API_KEY: '{{resolve:ssm:/coinbase_pro/api_keys/trade/key:1}}' 
          CBP_API_KEY_PASSPHRASE: '{{resolve:ssm:/coinbase_pro/api_keys/trade/passphrase:1}}' 
          CBP_API_KEY_SECRET: '{{resolve:ssm:/coinbase_pro/api_keys/trade/secret:1}}' 
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(30 0 * * ? *)
            Name: CoinbaseProTradeBtcSchedule
            Description: execution schedule for exchanging BTC to USD on Coinbase Pro
            Enabled: True
